name: Build docker image

on:
  push:
    # paths: [Dockerfile]

jobs:
  build-image:
    name: Build docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read

    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ github.repository }}

      # - name: Build and push Docker image
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: .
      #     tags: ${{ steps.meta.outputs.tags }}
      #     labels: ${{ steps.meta.outputs.labels }}

      - name: Notify via Slack
        # v1.15.0
        # https://github.com/slackapi/slack-github-action/commit/d5d276d7ae0f38f29322b80da9baf985cc80f8b1
        # uses: slackapi/slack-github-action@d5d276d7ae0f38f29322b80da9baf985cc80f8b1
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: github
          SLACK_COLOR: ${{ job.status }}
          SLACK_MESSAGE: Test message. Tags `${{ steps.meta.outputs.tags }}`
          SLACK_TITLE: Test title
          SLACK_USERNAME: github-bot
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        # with:
        #   channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
        #   slack-message: 'Test message. Tags `${{ steps.meta.outputs.tags }}`'
        # env:
        #   SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
